CREATE TABLE keyword_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_keyword_categories PRIMARY KEY (id)
);

ALTER TABLE keywords
    ADD category_id BIGINT;

ALTER TABLE keyword_categories
    ADD CONSTRAINT uc_keyword_categories_category UNIQUE (name);

ALTER TABLE keywords
    ADD CONSTRAINT FK_KEYWORDS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES keyword_categories (id);

-- Migrate the keyword categories
insert into keyword_categories (name)
select distinct(category) from keywords;

update keywords
set category_id = c.id
from (select id, name from keyword_categories) as c
where keywords.category = c.name
;

ALTER TABLE keywords
    ALTER COLUMN category_id SET NOT NULL;

ALTER TABLE keywords
    DROP COLUMN category;

CREATE INDEX idx_keyword ON keywords (category_id, keyword);