package com.decibeltx.studytracker.events;

public enum EventType {

  // For testing only
  TEST_EVENT,

  // Study events
  NEW_STUDY,
  UPDATED_STUDY,
  DELETED_STUDY,
  STUDY_STATUS_CHANGED,
  FILE_UPLOADED,
  NEW_STUDY_CONCLUSIONS,
  EDITED_STUDY_CONCLUSIONS,
  DELETED_STUDY_CONCLUSIONS,
  NEW_COMMENT,
  EDITED_COMMENT,
  DELETED_COMMENT,
  NEW_STUDY_RELATIONSHIP,
  UPDATED_STUDY_RELATIONSHIP,
  DELETED_STUDY_RELATIONSHIP,
  NEW_STUDY_EXTERNAL_LINK,
  UPDATED_STUDY_EXTERNAL_LINK,
  DELETED_STUDY_EXTERNAL_LINK,

  // Assay Events
  NEW_ASSAY,
  UPDATED_ASSAY,
  DELETED_ASSAY,
  ASSAY_STATUS_CHANGED,

  // Assay Tasks
  ASSAY_TASK_ADDED,
  ASSAY_TASK_UPDATED,
  ASSAY_TASK_DELETED,

  // Assay Type Events
  NEW_ASSAY_TYPE,
  UPDATED_ASSAY_TYPE,
  DELETED_ASSAY_TYPE,

  //Program Events
  NEW_PROGRAM,
  UPDATED_PROGRAM,
  DELETED_PROGRAM,

  // Users
  NEW_USER,
  UPDATED_USER,
  DELETED_USER,

  //EntryTemplate events
  NEW_ENTRY_TEMPLATE,
  UPDATED_ENTRY_TEMPLATE
}
