spring:

  application:
    name: Study Tracker

  data:
    web:
      pageable:
        default-page-size: 100

  datasource:
    platform: postgres
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    user: ${db.username}
    password: ${db.password}
    url: ${db.url}
    locations: classpath:db/migration

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    prefix: classpath:/

server:
  error:
    whitelabel:
      enabled: false

springdoc:
  packagesToScan: io.studytracker.controller.api
  pathsToMatch: /api/**

application:
  host-name: localhost

db:
  username: studytracker
  password: studytracker
  host: localhost
  name: study-tracker
  port: 5432
  url: jdbc:postgresql://${db.host}:${db.port}/${db.name}

notebook:
  mode: none

benchling:
  tenant-name:
  root-url: https://${benchling.tenant-name}.benchling.com
  root-folder-url: ${benchling.root-url}/${benchling.tenant-name}/f_
  api.root-url: ${benchling.root-url}/api/v2


storage:
  mode: local
  use-existing: false
  max-folder-read-depth: 3
  temp-dir: /tmp
  local-dir: ${storage.temp-dir}

egnyte:
  qps: 1

study:
  default-code-prefix: ST
  default-external-code-prefix: EX
  code-counter-start: 10000
