package com.decibeltx.studytracker.core.events.type;

public enum EventType {

  // Study events
  NEW_STUDY,
  UPDATED_STUDY,
  DELETED_STUDY,
  STUDY_STATUS_CHANGED,
  FILE_UPLOADED,
  NEW_STUDY_CONCLUSIONS,
  EDITED_STUDY_CONCLUSIONS,
  DELETED_STUDY_CONCLUSIONS,
  NEW_COMMENT,
  EDITED_COMMENT,
  DELETED_COMMENT,
  NEW_STUDY_RELATIONSHIP,
  UPDATED_STUDY_RELATIONSHIP,
  DELETED_STUDY_RELATIONSHIP,
  NEW_STUDY_EXTERNAL_LINK,
  UPDATED_STUDY_EXTERNAL_LINK,
  DELETED_STUDY_EXTERNAL_LINK,

  // Assay Events
  NEW_ASSAY,
  UPDATED_ASSAY,
  DELETED_ASSAY,
  ASSAY_STATUS_CHANGED,

  //Program Events
  NEW_PROGRAM,
  UPDATED_PROGRAM,
  DELETED_PROGRAM

}
