CREATE TABLE activity
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    program_id BIGINT,
    study_id   BIGINT,
    assay_id   BIGINT,
    event_type VARCHAR(255)                            NOT NULL,
    data       JSON,
    user_id    BIGINT                                  NOT NULL,
    date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT PK_ACTIVITY PRIMARY KEY (id)
);

CREATE TABLE assay_tasks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    label            VARCHAR(255)                            NOT NULL,
    task_order       INTEGER                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    assay_id         BIGINT                                  NOT NULL,
    created_by       BIGINT                                  NOT NULL,
    last_modified_by BIGINT                                  NOT NULL,
    assigned_to      BIGINT,
    due_date         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT PK_ASSAY_TASKS PRIMARY KEY (id)
);

CREATE TABLE assay_type_fields
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    display_name  VARCHAR(255)                            NOT NULL,
    field_name    VARCHAR(255)                            NOT NULL,
    type          VARCHAR(255)                            NOT NULL,
    required      BOOLEAN                                 NOT NULL,
    description   VARCHAR(1024),
    active        BOOLEAN                                 NOT NULL,
    assay_type_id BIGINT                                  NOT NULL,
    CONSTRAINT PK_ASSAY_TYPE_FIELDS PRIMARY KEY (id)
);

CREATE TABLE assay_type_tasks
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status        VARCHAR(255)                            NOT NULL,
    label         VARCHAR(255)                            NOT NULL,
    task_order    INTEGER                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    assay_type_id BIGINT                                  NOT NULL,
    CONSTRAINT PK_ASSAY_TYPE_TASKS PRIMARY KEY (id)
);

CREATE TABLE assay_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024)                           NOT NULL,
    active      BOOLEAN                                 NOT NULL,
    attributes  JSON,
    CONSTRAINT PK_ASSAY_TYPES PRIMARY KEY (id)
);

CREATE TABLE assay_users
(
    assay_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT PK_ASSAY_USERS PRIMARY KEY (assay_id, user_id)
);

CREATE TABLE assays
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    assay_type_id      BIGINT                                  NOT NULL,
    study_id           BIGINT                                  NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    code               VARCHAR(255)                            NOT NULL,
    description        TEXT                                    NOT NULL,
    created_by         BIGINT                                  NOT NULL,
    last_modified_by   BIGINT                                  NOT NULL,
    owner              BIGINT                                  NOT NULL,
    start_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date           TIMESTAMP WITHOUT TIME ZONE,
    notebook_folder_id BIGINT,
    storage_folder_id  BIGINT,
    active             BOOLEAN                                 NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    fields             JSON,
    attributes         JSON,
    CONSTRAINT PK_ASSAYS PRIMARY KEY (id)
);

CREATE TABLE collaborators
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label                 VARCHAR(255)                            NOT NULL,
    organization_name     VARCHAR(255)                            NOT NULL,
    organization_location VARCHAR(255),
    contact_person_name   VARCHAR(255),
    contact_email         VARCHAR(255),
    code                  VARCHAR(255)                            NOT NULL,
    active                BOOLEAN                                 NOT NULL,
    CONSTRAINT PK_COLLABORATORS PRIMARY KEY (id)
);

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    study_id   BIGINT                                  NOT NULL,
    text       TEXT                            NOT NULL,
    created_by BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT PK_COMMENTS PRIMARY KEY (id)
);

CREATE TABLE eln_folders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url          VARCHAR(1024)                           NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    path         VARCHAR(1024),
    reference_id VARCHAR(255),
    CONSTRAINT PK_ELN_FOLDERS PRIMARY KEY (id)
);

CREATE TABLE external_links
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    label    VARCHAR(255)                            NOT NULL,
    url      VARCHAR(1024)                           NOT NULL,
    study_id BIGINT                                  NOT NULL,
    CONSTRAINT PK_EXTERNAL_LINKS PRIMARY KEY (id)
);

CREATE TABLE file_store_folders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url          VARCHAR(1024),
    name         VARCHAR(255)                            NOT NULL,
    path         VARCHAR(1024)                            NOT NULL,
    reference_id VARCHAR(255),
    CONSTRAINT PK_FILE_STORE_FOLDERS PRIMARY KEY (id)
);

CREATE TABLE keywords
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    keyword  VARCHAR(255)                            NOT NULL,
    category VARCHAR(255)                            NOT NULL,
    CONSTRAINT PK_KEYWORDS PRIMARY KEY (id)
);

CREATE TABLE notebook_entry_templates
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    template_id      VARCHAR(255)                            NOT NULL,
    created_by       BIGINT                                  NOT NULL,
    last_modified_by BIGINT                                  NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    active           BOOLEAN                                 NOT NULL,
    CONSTRAINT PK_NOTEBOOK_ENTRY_TEMPLATES PRIMARY KEY (id)
);

CREATE TABLE programs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code               VARCHAR(255)                            NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    description        TEXT,
    created_by         BIGINT                                  NOT NULL,
    last_modified_by   BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    notebook_folder_id BIGINT,
    storage_folder_id  BIGINT,
    active             BOOLEAN                                 NOT NULL,
    attributes         JSON,
    CONSTRAINT PK_PROGRAMS PRIMARY KEY (id)
);

CREATE TABLE studies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code               VARCHAR(255)                            NOT NULL,
    external_code      VARCHAR(255),
    status             VARCHAR(255)                            NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    program_id         BIGINT                                  NOT NULL,
    description        TEXT                                    NOT NULL,
    collaborator_id    BIGINT,
    legacy             BOOLEAN                                 NOT NULL,
    active             BOOLEAN                                 NOT NULL,
    notebook_folder_id BIGINT,
    storage_folder_id  BIGINT,
    created_by         BIGINT                                  NOT NULL,
    last_modified_by   BIGINT                                  NOT NULL,
    start_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date           TIMESTAMP WITHOUT TIME ZONE,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    owner              BIGINT                                  NOT NULL,
    attributes         JSON,
    CONSTRAINT PK_STUDIES PRIMARY KEY (id)
);

CREATE TABLE study_conclusions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content          TEXT                                    NOT NULL,
    created_by       BIGINT                                  NOT NULL,
    last_modified_by BIGINT                                  NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    study_id         BIGINT                                  NOT NULL,
    CONSTRAINT PK_STUDY_CONCLUSIONS PRIMARY KEY (id)
);

CREATE TABLE study_keywords
(
    keyword_id BIGINT NOT NULL,
    study_id   BIGINT NOT NULL,
    CONSTRAINT PK_STUDY_KEYWORDS PRIMARY KEY (keyword_id, study_id)
);

CREATE TABLE study_relationships
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            VARCHAR(255)                            NOT NULL,
    source_study_id BIGINT                                  NOT NULL,
    target_study_id BIGINT                                  NOT NULL,
    CONSTRAINT PK_STUDY_RELATIONSHIPS PRIMARY KEY (id)
);

CREATE TABLE study_users
(
    study_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT PK_STUDY_USERS PRIMARY KEY (study_id, user_id)
);

CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username            VARCHAR(255)                            NOT NULL,
    password            VARCHAR(255),
    department          VARCHAR(255),
    title               VARCHAR(255),
    display_name        VARCHAR(255)                            NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    attributes          JSON,
    admin               BOOLEAN                                 NOT NULL,
    active              BOOLEAN                                 NOT NULL,
    locked              BOOLEAN                                 NOT NULL,
    expired             BOOLEAN                                 NOT NULL,
    credentials_expired BOOLEAN                                 NOT NULL,
    configuration       JSON,
    CONSTRAINT PK_USERS PRIMARY KEY (id)
);

ALTER TABLE assays
    ADD CONSTRAINT UC_ASSAYS_CODE UNIQUE (code);

ALTER TABLE assay_types
    ADD CONSTRAINT UC_ASSAY_TYPES_NAME UNIQUE (name);

ALTER TABLE collaborators
    ADD CONSTRAINT UC_COLLABORATORS_LABEL UNIQUE (label);

ALTER TABLE notebook_entry_templates
    ADD CONSTRAINT UC_NOTEBOOK_ENTRY_TEMPLATES_NAME UNIQUE (name);

ALTER TABLE notebook_entry_templates
    ADD CONSTRAINT UC_NOTEBOOK_ENTRY_TEMPLATES_TEMPLATE UNIQUE (template_id);

ALTER TABLE programs
    ADD CONSTRAINT UC_PROGRAMS_NAME UNIQUE (name);

ALTER TABLE studies
    ADD CONSTRAINT UC_STUDIES_CODE UNIQUE (code);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_EMAIL UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT UC_USERS_USERNAME UNIQUE (username);

CREATE
INDEX IDX_PROGRAM_NAME ON programs (name);

CREATE
INDEX IDX_STUDY_CODE ON studies (code);

CREATE
INDEX IDX_STUDY_NAME ON studies (name);

ALTER TABLE activity
    ADD CONSTRAINT FK_ACTIVITY_ON_ASSAY FOREIGN KEY (assay_id) REFERENCES assays (id);

ALTER TABLE activity
    ADD CONSTRAINT FK_ACTIVITY_ON_PROGRAM FOREIGN KEY (program_id) REFERENCES programs (id);

ALTER TABLE activity
    ADD CONSTRAINT FK_ACTIVITY_ON_STUDY FOREIGN KEY (study_id) REFERENCES studies (id);

ALTER TABLE activity
    ADD CONSTRAINT FK_ACTIVITY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE assays
    ADD CONSTRAINT FK_ASSAYS_ON_ASSAY_TYPE FOREIGN KEY (assay_type_id) REFERENCES assay_types (id);

ALTER TABLE assays
    ADD CONSTRAINT FK_ASSAYS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE assays
    ADD CONSTRAINT FK_ASSAYS_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES users (id);

ALTER TABLE assays
    ADD CONSTRAINT FK_ASSAYS_ON_NOTEBOOK_FOLDER FOREIGN KEY (notebook_folder_id) REFERENCES eln_folders (id);

ALTER TABLE assays
    ADD CONSTRAINT FK_ASSAYS_ON_OWNER FOREIGN KEY (owner) REFERENCES users (id);

ALTER TABLE assays
    ADD CONSTRAINT FK_ASSAYS_ON_STORAGE_FOLDER FOREIGN KEY (storage_folder_id) REFERENCES file_store_folders (id);

ALTER TABLE assays
    ADD CONSTRAINT FK_ASSAYS_ON_STUDY FOREIGN KEY (study_id) REFERENCES studies (id);

ALTER TABLE assay_tasks
    ADD CONSTRAINT FK_ASSAY_TASKS_ON_ASSAY FOREIGN KEY (assay_id) REFERENCES assays (id);

ALTER TABLE assay_tasks
    ADD CONSTRAINT FK_ASSAY_TASKS_ON_ASSIGNED_TO FOREIGN KEY (assigned_to) REFERENCES users (id);

ALTER TABLE assay_tasks
    ADD CONSTRAINT FK_ASSAY_TASKS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE assay_tasks
    ADD CONSTRAINT FK_ASSAY_TASKS_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES users (id);

ALTER TABLE assay_type_fields
    ADD CONSTRAINT FK_ASSAY_TYPE_FIELDS_ON_ASSAY_TYPE FOREIGN KEY (assay_type_id) REFERENCES assay_types (id);

ALTER TABLE assay_type_tasks
    ADD CONSTRAINT FK_ASSAY_TYPE_TASKS_ON_ASSAY_TYPE FOREIGN KEY (assay_type_id) REFERENCES assay_types (id);

ALTER TABLE assay_users
    ADD CONSTRAINT FK_ASSUSE_ON_ASSAY FOREIGN KEY (assay_id) REFERENCES assays (id);

ALTER TABLE assay_users
    ADD CONSTRAINT FK_ASSUSE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_STUDY FOREIGN KEY (study_id) REFERENCES studies (id);

ALTER TABLE external_links
    ADD CONSTRAINT FK_EXTERNAL_LINKS_ON_STUDY FOREIGN KEY (study_id) REFERENCES studies (id);

ALTER TABLE notebook_entry_templates
    ADD CONSTRAINT FK_NOTEBOOK_ENTRY_TEMPLATES_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE notebook_entry_templates
    ADD CONSTRAINT FK_NOTEBOOK_ENTRY_TEMPLATES_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES users (id);

ALTER TABLE programs
    ADD CONSTRAINT FK_PROGRAMS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE programs
    ADD CONSTRAINT FK_PROGRAMS_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES users (id);

ALTER TABLE programs
    ADD CONSTRAINT FK_PROGRAMS_ON_NOTEBOOK_FOLDER FOREIGN KEY (notebook_folder_id) REFERENCES eln_folders (id);

ALTER TABLE programs
    ADD CONSTRAINT FK_PROGRAMS_ON_STORAGE_FOLDER FOREIGN KEY (storage_folder_id) REFERENCES file_store_folders (id);

ALTER TABLE studies
    ADD CONSTRAINT FK_STUDIES_ON_COLLABORATOR FOREIGN KEY (collaborator_id) REFERENCES collaborators (id);

ALTER TABLE studies
    ADD CONSTRAINT FK_STUDIES_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE studies
    ADD CONSTRAINT FK_STUDIES_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES users (id);

ALTER TABLE studies
    ADD CONSTRAINT FK_STUDIES_ON_NOTEBOOK_FOLDER FOREIGN KEY (notebook_folder_id) REFERENCES eln_folders (id);

ALTER TABLE studies
    ADD CONSTRAINT FK_STUDIES_ON_OWNER FOREIGN KEY (owner) REFERENCES users (id);

ALTER TABLE studies
    ADD CONSTRAINT FK_STUDIES_ON_PROGRAM FOREIGN KEY (program_id) REFERENCES programs (id);

ALTER TABLE studies
    ADD CONSTRAINT FK_STUDIES_ON_STORAGE_FOLDER FOREIGN KEY (storage_folder_id) REFERENCES file_store_folders (id);

ALTER TABLE study_conclusions
    ADD CONSTRAINT FK_STUDY_CONCLUSIONS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE study_conclusions
    ADD CONSTRAINT FK_STUDY_CONCLUSIONS_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES users (id);

ALTER TABLE study_conclusions
    ADD CONSTRAINT FK_STUDY_CONCLUSIONS_ON_STUDY FOREIGN KEY (study_id) REFERENCES studies (id);

ALTER TABLE study_relationships
    ADD CONSTRAINT FK_STUDY_RELATIONSHIPS_ON_SOURCE_STUDY FOREIGN KEY (source_study_id) REFERENCES studies (id);

ALTER TABLE study_relationships
    ADD CONSTRAINT FK_STUDY_RELATIONSHIPS_ON_TARGET_STUDY FOREIGN KEY (target_study_id) REFERENCES studies (id);

ALTER TABLE study_keywords
    ADD CONSTRAINT FK_STUKEY_ON_KEYWORD FOREIGN KEY (keyword_id) REFERENCES keywords (id);

ALTER TABLE study_keywords
    ADD CONSTRAINT FK_STUKEY_ON_STUDY FOREIGN KEY (study_id) REFERENCES studies (id);

ALTER TABLE study_users
    ADD CONSTRAINT FK_STUUSE_ON_STUDY FOREIGN KEY (study_id) REFERENCES studies (id);

ALTER TABLE study_users
    ADD CONSTRAINT FK_STUUSE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE SEQUENCE hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;